### ISSUE TITLE
Make enemy art

### ISSUE THREAD

**Issue by istare21** [AILab-FOI/PRRI-MMORPG2024#1]
3 different sprites is enough for now

**Comment by aslavicek21** [comment]
Napravljen 1 enemy type - "Blood acolyte"
Side i front view. Pitanje palete i koja verzija boja bolje izgleda.
![blood acolyte walk front](https://github.com/AILab-FOI/PRRI-MMORPG2024/assets/126473665/816b865b-f77d-47ab-a7d8-737e625e2996)
![Blood acolyte side walk L](https://github.com/AILab-FOI/PRRI-MMORPG2024/assets/126473665/99951d3f-9854-4fab-80be-0af4343267f8)

**Comment by istare21** [comment]
osobno mi 1 bolje izgleda. good work

**Comment by lrakic20** [comment]
Dog/Wolf Enemy Type - Animacije
https://github.com/AILab-FOI/PRRI-MMORPG2024/assets/126506140/10bca56f-f2ec-4988-b4e7-70a1f9787f44

**Comment by lrakic20** [comment]
Files:

[dog.zip](https://github.com/user-attachments/files/15834826/dog.zip)

**Comment by lrakic20** [comment]
Satyr Idle - Animacije

![Snimka zaslona 2024-06-14 142338](https://github.com/AILab-FOI/PRRI-MMORPG2024/assets/126506140/c606599b-4c27-48e1-ab26-16f392eafc9c)

[satyr.zip](https://github.com/user-attachments/files/15838021/satyr.zip)

**Comment by aslavicek21** [comment]
Stavljam ovdje zbog preglednosti.

[Blood acolyte - walking anim.zip](https://github.com/user-attachments/files/15839371/Blood.acolyte.-.walking.anim.zip)
[Blood acolyte - attack anim.zip](https://github.com/user-attachments/files/15839372/Blood.acolyte.-.attack.anim.zip)


https://github.com/AILab-FOI/PRRI-MMORPG2024/assets/126473665/43ff90fc-13d3-44d5-a662-94f6d0434fb0


https://github.com/AILab-FOI/PRRI-MMORPG2024/assets/126473665/c3745938-5064-494d-bcf5-1dbcb3ab16e6
