### ISSUE TITLE
Prikazivanje i trackanje inventorija

### ISSUE THREAD

**Issue by istare21** [AILab-FOI/PRRI-MMORPG2024#32]
- [x] Basically implementacija u DB?
- [x] prikazivanje inventory-ja preko teksta

**Comment by vvugrinec21** [comment]
Implementiran je osnovni model baze podataka za pohranu informacija o inventoryu.
Testovi su uspješno provedeni i funkcionalnost je potvrđena.

**Comment by vvugrinec21** [comment]
Implementiran je osnovni model baze podataka za pohranu informacija o inventoryu.
Testovi su uspješno provedeni i funkcionalnost je potvrđena.
