### ISSUE TITLE
Make sound effects

### ISSUE THREAD

**Issue by istare21** [AILab-FOI/PRRI-MMORPG2024#9]
Attack, Hurt, Enemy Death for start. Možda neki UI bipovi.

https://sfbgames.itch.io/chiptone kao prijedlog

**Comment by Vanquility** [comment]
Sounds : Attack,Hurt,Death,UI click
[Sounds v.1.zip](https://github.com/AILab-FOI/PRRI-MMORPG2024/files/15287270/Sounds.v.1.zip)

**Comment by mvrscak21** [comment]
[SoundsV2]
[SoundV2.zip](https://github.com/user-attachments/files/15788884/SoundV2.zip)
